version: '3.8'

services:
  product-service:
    build: ./products-service
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PRODUCT_SERVICE_URL=http://product-service:8081/api/products
    depends_on:
      - product-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
